# Generated by Django 3.0.8 on 2020-08-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0003_auto_20200818_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum_app.forum'),
        ),
    ]
